"
" ~/etc/vim/vimrc
" Usr Config - Vimrc
" 
" Made by Zhu Zhan Yan
" Copyright (c) 2016. All Rights Reserved.
"

"Var
let g:mapleader = ','

"Set
set nocompatible
set autoread
set wildmenu
set ruler
set number
set backspace=start,eol,indent
set smartcase
set hlsearch
set incsearch
set magic
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent
set noshowmode
set showtabline=2

"File
set encoding=utf8
set fileformats=unix,dos,mac
filetype plugin on
filetype plugin indent on

"Clr
set background=dark
syntax enable
colorscheme desert

"Kbd
nmap <leader>a :args<cr>
nmap <leader>aa :argedit
nmap <leader>ad :argdelete %<cr>
nmap <leader>an :next<cr>
nmap <leader>aN :Next<cr>
nmap <leader>ar :rewind<cr>
nmap <leader>al :last<cr>
nmap <leader>ad :argdo
nmap <leader>b :ls<cr>
nmap <leader>bd :bdelete<cr>
nmap <leader>bs :sbuffer<cr>
nmap <leader>bn :bnext<cr>
nmap <leader>bN :bNext<cr>
nmap <leader>bl :blast<cr>
nmap <leader>br :brewind<cr>
nmap <leader>t :tabs<cr>
nmap <leader>tt :tabnew<cr>
nmap <leader>td :tabclose<cr>
nmap <leader>to :tabonly<cr>
nmap <leader>tn :tabnext<cr>
nmap <leader>tN :tabNext<cr>
nmap <leader>tr :tabrewind<cr>
nmap <leader>tl :tablast<cr>
nmap <leader>t[ :tabmove -1<cr>
nmap <leader>t] :tabmove +1<cr>
nmap <leader>s :setl spell<cr>
nmap <leader>sn ]s
nmap <leader>sN [s
nmap <leader>ss zg
nmap <leader>sS zuw
nmap <leader>sr z=

"Src
source ~/etc/vim/vim_plug.vim
