"
" ~/etc/vim/vimrc
" Usr Config - Vimrc
" 
" Made by Zhu Zhan Yan
" Copyright (c) 2016. All Rights Reserved.
"

"Var
let g:mapleader = ','

"Set
set nocompatible
set autoread
set wildmenu
set ruler
set number
set backspace=start,eol,indent
set smartcase
set hlsearch
set incsearch
set magic
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set smartindent
set noshowmode
set showtabline=2

"File
set encoding=utf8
set fileformats=unix,dos,mac
filetype plugin on
filetype plugin indent on

"Clr
set background=dark
syntax enable
colorscheme desert

"Kbd
nmap <leader>b :ls<cr>
nmap <leader>bd :bdelete<cr>
nmap <leader>bs :sbuffer<cr>
nmap <leader>bn :bnext<cr>
nmap <leader>bN :bNext<cr>
nmap <leader>bl :blast<cr>
nmap <leader>br :brewind<cr>
nmap <leader>t :tabs<cr>
nmap <leader>tt :tabnew<cr>
nmap <leader>td :tabclose<cr>
nmap <leader>to :tabonly<cr>
nmap <leader>tn :tabnext<cr>
nmap <leader>tN :tabNext<cr>
nmap <leader>tr :tabrewind<cr>
nmap <leader>tl :tablast<cr>
nmap <leader>t[ :tabmove -1
nmap <leader>t] :tabmove +1
nmap <leader>s :setl spell
nmap <leader>sn ]s
nmap <leader>sN [s
nmap <leader>ss zg
nmap <leader>sS zuw
nmap <leader>sr z=

"Plug
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'scrooloose/syntastic'
Plugin 'Shougo/neocomplete.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'vim-airline/vim-airline'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-fugitive'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'majutsushi/tagbar'
Plugin 'SirVir/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'edkolev/tmuxline.vim'
Plugin 'Shougo/vimproc.vim'
Plugin 'neitanod/vim-clevertab'
call vundle#end()

let g:airline_detect_modified=1
let g:airline_detect_paste=1
let g:airline_detect_crypt=1
let g:airline_detect_spell=1
let g:airline_powerline_fonts=1
let g:airline_powerline_font=1
let g:airline#extensions#branch#enabled=1
let g:airline#extensions#syntastic#enabled=1
let g:airline#extensions#ctrlp#color_template='visual'
let g:airline#extensions#ctrlp#dshow_adjacent_modes=1
let g:airline#extensions#tabline#enabled=1

set statusline+=%#warning_msg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list=1
let g:syntastic_auto_loc_list=1
let g:syntastic_check_on_open=1
let g:syntastic_check_on_wq=0
let g:syntastic_sort_aggregated_errors=1
let g:syntastic_auto_jump=3
nmap <leader>pss :SyntasticCheck<cr>
nmap <leader>psl :Errors<cr>

colorscheme solarized

let g:neocomplete#enable_at_startip=1
let g:neocomplete#max_list=100
let g:neocomplete#max_keyword_width=1000
let g:neocomplete#auto_completetion_start_length=2
let g:neocomplete#min_keyword_length=2
let g:neocomplete#enable_ignore_case=1
