
#Paths
export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH=/Users/zzy/.oh-my-zsh

ZSH_THEME="robbyrussell"

DISABLE_AUTO_UPDATE="true"

HIST_STAMPS="dd/mm/yyyy"

#Plugin Configuration
plugins=(
    vi-mode
    git-fast
    osx
    perl
    python
    tmux
)
#Plugin Tmux
ZSH_TMUX_AUTOSTART=true;
DISABLE_AUTO_TITLE="true"

source $ZSH/oh-my-zsh.sh

# User configuration

export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8

if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='vim'
else
    export EDITOR='nvim'
fi


# Compilation flags
export ARCHFLAGS="-arch x86_64"

# SSH Key Path export SSH_KEY_PATH="~/.ssh/rsa_id"

alias vim="nvim"
alias py="python3"


