
# zshrc
# ZSH Configuration file
#

#Paths
export PATH="$HOME/.rvm/bin:$PATH"
export PATH="$HOME/bin:/usr/local/bin:$PATH"
export MANPATH="/usr/local/man:$MANPATH"
export SSH_KEY_PATH="~/.ssh/rsa_id"

#Locale
export LANG="en_US.UTF-8"

#Programs
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='vim'
    export VISUAL="vim"
else
    export EDITOR='nvim'
    export VISUAL="nvim"
fi
alias vim="nvim"
alias py="python3"

# Compilation flags
export ARCHFLAGS="-arch x86_64"

#Plugin Configuration
HISTFILE="$HOME/.zsh_history"
HIST_STAMPS="dd/mm/yyyy"
HISTSIZE=100000
SAVEHIST=100000
setopt share_history
setopt inc_append_history

source ~/.zplug/init.zsh
zplug "plugins/vi-mode", from:oh-my-zsh
zplug "plugins/git-fast", from:oh-my-zsh
zplug "plugins/tmux", from:oh-my-zsh
zplug "mafredri/zsh-async"
zplug "miekg/lean", as:theme, use:"lean.plugin.zsh"

ZSH_TMUX_AUTOSTART=true

#Lean Prompt Configuration
prompt_lean_python_venv_status()
{
    if [ -n "$VIRTUAL_ENV" ]
    then 
        printf " venv "
    fi
}

PROMPT_LEAN_TMUX=">"
PROMPT_LEAN_VIMODE="1"
PROMPT_LEAN_NOTITLE="1"
PROMPT_LEAN_NOTITLE="1"
PROMPT_LEAN_COLOR1="136"
PROMPT_LEAN_COLOR2="61"
PROMPT_LEAN_RIGHT="prompt_lean_python_venv_status"

zplug load

#External Scripts
source $HOME/.rvm/scripts/rvm #Ruby Version Manager
