#
# ~/etc/bash/bash_profile
# Usr Config - Bash Profile
# 
# Made by Zhu Zhan Yan
# Copyright (c) 2016. All Rights Reserved.
#

#Src>Bashrc
source ${HOME}/.bashrc

#Pg>Xsvr
if ! xset q &>/dev/null
then
    startx
fi
