#
# ~/etc/bash/bashrc
# Usr Config - Bashrc
# 
# Made by Zhu Zhan Yan
# Copyright (c) 2016. All Rights Reserved.
#


#Set
#Set>CmdEd
set -o vi

#Var
export PAGER="less"
export EDITOR="vim"
export VISUAL="vim"
export BROWSER="w3m"
#Var>XDG
export XDG_CONFIG_HOME="${HOME}/etc"
export XDG_DESKTOP_DIR="${HOME}/wsp"
export XDG_DOCUMENTS_DIR="${HOME}/doc"
export XDG_DOWNLOAD_DIe="${HOME}/dwld"
export XDG_MUSIC_DIR="${HOME}/mdi/msic"

#Src>Alias
if [ -x ${HOME}/etc/bash/bash_alias ]
then
    source ${HOME}/etc/bash/bash_alias 
fi

#Prg>Tmux
if [ -z ${TMUX} ] && xset q &>/dev/null
then
    tmux
fi

